Add Fedora build instructions
occ-ai/obs-ocr pull request #8
Opened 2024-01-26 16:04 UTC by royshil

2024-01-26 16:30 UTC, umireon commented
Building on Fedora now

2024-01-26 16:39 UTC, umireon requested changes

2024-01-26 16:39 UTC, umireon commented on docs/BUILD-FEDORA.md
> +git clone https://github.com/obs-ai/obs-ocr.git
```suggestion
git clone https://github.com/occ-ai/obs-ocr.git
```

2024-01-26 16:39 UTC, umireon commented on docs/BUILD-FEDORA.md
> +git submodule update --init
inja cannot be cloned. Please change the repository URL on .gitmodules to be an HTTPS URL.

2024-01-26 16:40 UTC, umireon commented
```
[umireon@fedora-from-source obs-ocr]$ .github/scripts/build-linux --skip-deps
   =>   Configuring obs-ocr...
Preset CMake variables:

  ENABLE_FRONTEND_API:BOOL="TRUE"
  ENABLE_QT:BOOL="TRUE"

-- Could NOT find XKB (missing: XKB_LIBRARY XKB_INCLUDE_DIR) (Required is at least version "0.5.0")
Config:
 target        = single_include/inja/inja.hpp
 working_dir   = /home/umireon/obs-ocr/vendor/inja
 include_paths = []
Creating amalgamation:
 - processing "inja/inja.hpp"
...done!

Files processed: ['inja/inja.hpp']
Files included: ['inja/inja.hpp', 'inja/environment.hpp', 'inja/config.hpp', 'inja/template.hpp', 'inja/node.hpp', 'inja/function_storage.hpp', 'inja/utils.hpp', 'inja/exceptions.hpp', 'inja/statistics.hpp', 'inja/parser.hpp', 'inja/lexer.hpp', 'inja/token.hpp', 'inja/renderer.hpp']

-- Configuring done (0.3s)
-- Generating done (0.0s)
-- Build files have been written to: /home/umireon/obs-ocr/build_x86_64
   =>   Building obs-ocr...
[9/10] Building CXX object CMakeFiles/obs-ocr.dir/src/tesseract-ocr-utils.cpp.o
FAILED: CMakeFiles/obs-ocr.dir/src/tesseract-ocr-utils.cpp.o 
/usr/bin/c++ -DHAVE_OBSCONFIG_H -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DSIMDE_ENABLE_OPENMP -Dobs_ocr_EXPORTS -I/home/umireon/obs-ocr/build_x86_64 -I/home/umireon/obs-ocr -I/home/umireon/obs-ocr/build_x86_64/obs-ocr_autogen/include -I/home/umireon/obs-ocr/vendor/inja/include -I/home/umireon/obs-ocr/vendor/inja/third_party/include -I/home/umireon/obs-ocr/src -isystem /usr/include/obs -isystem /usr/include/qt6/QtCore -isystem /usr/include/qt6 -isystem /usr/lib64/qt6/mkspecs/linux-g++ -isystem /usr/include/qt6/QtWidgets -isystem /usr/include/qt6/QtGui -isystem /home/umireon/obs-ocr/build_x86_64/_deps/opencv-src/include/opencv4 -isystem /home/umireon/obs-ocr/build_x86_64/_deps/tesseract-src/include -O2 -g -DNDEBUG -std=c++17 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -fdiagnostics-color=always -fopenmp-simd -fno-strict-aliasing -Wdeprecated-declarations -Wempty-body -Wenum-conversion -Werror=return-type -Wextra -Wformat -Wformat-security -Wno-conversion -Wno-float-conversion -Wno-implicit-fallthrough -Wno-missing-braces -Wno-missing-field-initializers -Wno-shadow -Wno-sign-conversion -Wno-trigraphs -Wno-unknown-pragmas -Wno-unused-function -Wno-unused-label -Wparentheses -Wshadow -Wuninitialized -Wunreachable-code -Wunused-parameter -Wunused-value -Wunused-variable -Wvla -Wconversion -Wfloat-conversion -Winvalid-offsetof -Wno-overloaded-virtual -Wno-error=maybe-uninitialized -Winfinite-recursion -mmmx -msse -msse2 -Werror -MD -MT CMakeFiles/obs-ocr.dir/src/tesseract-ocr-utils.cpp.o -MF CMakeFiles/obs-ocr.dir/src/tesseract-ocr-utils.cpp.o.d -o CMakeFiles/obs-ocr.dir/src/tesseract-ocr-utils.cpp.o -c /home/umireon/obs-ocr/src/tesseract-ocr-utils.cpp
In file included from /home/umireon/obs-ocr/vendor/inja/include/inja/utils.hpp:10,
                 from /home/umireon/obs-ocr/vendor/inja/include/inja/node.hpp:9,
                 from /home/umireon/obs-ocr/vendor/inja/include/inja/template.hpp:9,
                 from /home/umireon/obs-ocr/vendor/inja/include/inja/config.hpp:7,
                 from /home/umireon/obs-ocr/vendor/inja/include/inja/environment.hpp:11,
                 from /home/umireon/obs-ocr/vendor/inja/include/inja/inja.hpp:54,
                 from /home/umireon/obs-ocr/src/tesseract-ocr-utils.cpp:12:
/home/umireon/obs-ocr/vendor/inja/include/inja/exceptions.hpp: In constructor ‘inja::InjaError::InjaError(const std::string&, const std::string&)’:
/home/umireon/obs-ocr/vendor/inja/include/inja/exceptions.hpp:20:66: error: declaration of ‘message’ shadows a member of ‘inja::InjaError’ [-Werror=shadow]
   20 |   explicit InjaError(const std::string& type, const std::string& message)
      |                                               ~~~~~~~~~~~~~~~~~~~^~~~~~~
/home/umireon/obs-ocr/vendor/inja/include/inja/exceptions.hpp:16:21: note: shadowed declaration is here
   16 |   const std::string message;
      |                     ^~~~~~~
/home/umireon/obs-ocr/vendor/inja/include/inja/exceptions.hpp:20:41: error: declaration of ‘type’ shadows a member of ‘inja::InjaError’ [-Werror=shadow]
   20 |   explicit InjaError(const std::string& type, const std::string& message)
      |                      ~~~~~~~~~~~~~~~~~~~^~~~
/home/umireon/obs-ocr/vendor/inja/include/inja/exceptions.hpp:15:21: note: shadowed declaration is here
   15 |   const std::string type;
      |                     ^~~~
/home/umireon/obs-ocr/vendor/inja/include/inja/exceptions.hpp: In constructor ‘inja::InjaError::InjaError(const std::string&, const std::string&)’:
/home/umireon/obs-ocr/vendor/inja/include/inja/exceptions.hpp:20:66: error: declaration of ‘message’ shadows a member of ‘inja::InjaError’ [-Werror=shadow]
   20 |   explicit InjaError(const std::string& type, const std::string& message)
      |                                               ~~~~~~~~~~~~~~~~~~~^~~~~~~
/home/umireon/obs-ocr/vendor/inja/include/inja/exceptions.hpp:16:21: note: shadowed declaration is here
   16 |   const std::string message;
      |                     ^~~~~~~
/home/umireon/obs-ocr/vendor/inja/include/inja/exceptions.hpp:20:41: error: declaration of ‘type’ shadows a member of ‘inja::InjaError’ [-Werror=shadow]
   20 |   explicit InjaError(const std::string& type, const std::string& message)
      |                      ~~~~~~~~~~~~~~~~~~~^~~~
/home/umireon/obs-ocr/vendor/inja/include/inja/exceptions.hpp:15:21: note: shadowed declaration is here
   15 |   const std::string type;
      |                     ^~~~
/home/umireon/obs-ocr/vendor/inja/include/inja/exceptions.hpp: In constructor ‘inja::InjaError::InjaError(const std::string&, const std::string&)’:
/home/umireon/obs-ocr/vendor/inja/include/inja/exceptions.hpp:20:66: error: declaration of ‘message’ shadows a member of ‘inja::InjaError’ [-Werror=shadow]
   20 |   explicit InjaError(const std::string& type, const std::string& message)
      |                                               ~~~~~~~~~~~~~~~~~~~^~~~~~~
/home/umireon/obs-ocr/vendor/inja/include/inja/exceptions.hpp:16:21: note: shadowed declaration is here
   16 |   const std::string message;
      |                     ^~~~~~~
/home/umireon/obs-ocr/vendor/inja/include/inja/exceptions.hpp:20:41: error: declaration of ‘type’ shadows a member of ‘inja::InjaError’ [-Werror=shadow]
   20 |   explicit InjaError(const std::string& type, const std::string& message)
      |                      ~~~~~~~~~~~~~~~~~~~^~~~
/home/umireon/obs-ocr/vendor/inja/include/inja/exceptions.hpp:15:21: note: shadowed declaration is here
   15 |   const std::string type;
      |                     ^~~~
/home/umireon/obs-ocr/vendor/inja/include/inja/exceptions.hpp: In constructor ‘inja::InjaError::InjaError(const std::string&, const std::string&, inja::SourceLocation)’:
/home/umireon/obs-ocr/vendor/inja/include/inja/exceptions.hpp:23:90: error: declaration of ‘location’ shadows a member of ‘inja::InjaError’ [-Werror=shadow]
   23 |   explicit InjaError(const std::string& type, const std::string& message, SourceLocation location)
      |                                                                           ~~~~~~~~~~~~~~~^~~~~~~~
/home/umireon/obs-ocr/vendor/inja/include/inja/exceptions.hpp:18:24: note: shadowed declaration is here
   18 |   const SourceLocation location;
      |                        ^~~~~~~~
/home/umireon/obs-ocr/vendor/inja/include/inja/exceptions.hpp:23:66: error: declaration of ‘message’ shadows a member of ‘inja::InjaError’ [-Werror=shadow]
   23 |   explicit InjaError(const std::string& type, const std::string& message, SourceLocation location)
      |                                               ~~~~~~~~~~~~~~~~~~~^~~~~~~
/home/umireon/obs-ocr/vendor/inja/include/inja/exceptions.hpp:16:21: note: shadowed declaration is here
   16 |   const std::string message;
      |                     ^~~~~~~
/home/umireon/obs-ocr/vendor/inja/include/inja/exceptions.hpp:23 [...]

2024-01-26 16:41 UTC, umireon commented
I cannot say that this plugin is ready for building on Fedora as I said.

2024-01-26 17:45 UTC, royshil commented
@umireon are you able to test again?
if this is possible in docker i can do it too

2024-01-26 17:50 UTC, umireon commented
Sure, I will try again soon

2024-01-26 17:54 UTC, umireon commented
```
[umireon@fedora-from-source obs-ocr]$ .github/scripts/build-linux --skip-deps
   =>   Configuring obs-ocr...
Preset CMake variables:

  ENABLE_FRONTEND_API:BOOL="TRUE"
  ENABLE_QT:BOOL="TRUE"

-- The C compiler identification is GNU 13.2.1
-- The CXX compiler identification is GNU 13.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Threads: TRUE  
-- Performing Test HAVE_STDATOMIC
-- Performing Test HAVE_STDATOMIC - Success
-- Qt version found: 6
-- Found OpenGL: /usr/lib64/libOpenGL.so   
-- Found WrapOpenGL: TRUE  
-- Could NOT find XKB (missing: XKB_LIBRARY XKB_INCLUDE_DIR) (Required is at least version "0.5.0")
-- Found WrapVulkanHeaders: /usr/include  
Config:
 target        = single_include/inja/inja.hpp
 working_dir   = /home/umireon/obs-ocr/vendor/inja
 include_paths = []
Creating amalgamation:
 - processing "inja/inja.hpp"
...done!

Files processed: ['inja/inja.hpp']
Files included: ['inja/inja.hpp', 'inja/environment.hpp', 'inja/config.hpp', 'inja/template.hpp', 'inja/node.hpp', 'inja/function_storage.hpp', 'inja/utils.hpp', 'inja/exceptions.hpp', 'inja/statistics.hpp', 'inja/parser.hpp', 'inja/lexer.hpp', 'inja/token.hpp', 'inja/renderer.hpp']

-- Configuring done (3.3s)
-- Generating done (0.0s)
-- Build files have been written to: /home/umireon/obs-ocr/build_x86_64
   =>   Building obs-ocr...
[9/10] Building CXX object CMakeFiles/obs-ocr.dir/src/tesseract-ocr-utils.cpp.o
FAILED: CMakeFiles/obs-ocr.dir/src/tesseract-ocr-utils.cpp.o 
/usr/bin/c++ -DHAVE_OBSCONFIG_H -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DSIMDE_ENABLE_OPENMP -Dobs_ocr_EXPORTS -I/home/umireon/obs-ocr/build_x86_64 -I/home/umireon/obs-ocr -I/home/umireon/obs-ocr/build_x86_64/obs-ocr_autogen/include -I/home/umireon/obs-ocr/vendor/inja/include -I/home/umireon/obs-ocr/vendor/inja/third_party/include -I/home/umireon/obs-ocr/src -isystem /usr/include/obs -isystem /usr/include/qt6/QtCore -isystem /usr/include/qt6 -isystem /usr/lib64/qt6/mkspecs/linux-g++ -isystem /usr/include/qt6/QtWidgets -isystem /usr/include/qt6/QtGui -isystem /home/umireon/obs-ocr/build_x86_64/_deps/opencv-src/include/opencv4 -isystem /home/umireon/obs-ocr/build_x86_64/_deps/tesseract-src/include -O2 -g -DNDEBUG -std=c++17 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -fdiagnostics-color=always -fopenmp-simd -fno-strict-aliasing -Wdeprecated-declarations -Wempty-body -Wenum-conversion -Werror=return-type -Wextra -Wformat -Wformat-security -Wno-conversion -Wno-float-conversion -Wno-implicit-fallthrough -Wno-missing-braces -Wno-missing-field-initializers -Wno-shadow -Wno-sign-conversion -Wno-trigraphs -Wno-unknown-pragmas -Wno-unused-function -Wno-unused-label -Wparentheses -Wshadow -Wuninitialized -Wunreachable-code -Wunused-parameter -Wunused-value -Wunused-variable -Wvla -Wconversion -Wfloat-conversion -Winvalid-offsetof -Wno-overloaded-virtual -Wno-error=maybe-uninitialized -Winfinite-recursion -mmmx -msse -msse2 -Werror -MD -MT CMakeFiles/obs-ocr.dir/src/tesseract-ocr-utils.cpp.o -MF CMakeFiles/obs-ocr.dir/src/tesseract-ocr-utils.cpp.o.d -o CMakeFiles/obs-ocr.dir/src/tesseract-ocr-utils.cpp.o -c /home/umireon/obs-ocr/src/tesseract-ocr-utils.cpp
In file included from /home/umireon/obs-ocr/vendor/inja/include/inja/utils.hpp:10,
                 from /home/umireon/obs-ocr/vendor/inja/include/inja/node.hpp:9,
                 from /home/umireon/obs-ocr/vendor/inja/include/inja/template.hpp:9,
                 from /home/umireon/obs-ocr/vendor/inja/include/inja/config.hpp:7,
                 from /home/umireon/obs-ocr/vendor/inja/include/inja/environment.hpp:11,
                 from /home/umireon/obs-ocr/vendor/inja/include/inja/inja.hpp:54,
                 from /home/umireon/obs-ocr/src/tesseract-ocr-utils.cpp:12:
/home/umireon/obs-ocr/vendor/inja/include/inja/exceptions.hpp: In constructor ‘inja::InjaError::InjaError(const std::string&, const std::string&)’:
/home/umireon/obs-ocr/vendor/inja/include/inja/exceptions.hpp:20:66: error: declaration of ‘message’ shadows a member of ‘inja::InjaError’ [-Werror=shadow]
   20 |   explicit InjaError(const std::string& type, const std::string& message)
      |                                               ~~~~~~~~~~~~~~~~~~~^~~~~~~
/home/umireon/obs-ocr/vendor/inja/include/inja/exceptions.hpp:16:21: note: shadowed declaration is here
   16 |   const std::string message;
      |                     ^~~~~~~
/home/umireon/obs-ocr/vendor/inja/include/inja/exceptions.hpp:20:41: error: declaration of ‘type’ shadows a member of ‘inja::InjaError’ [-Werror=shadow]
   20 |   explicit InjaError(const std::string& type, const std::string& message)
      |                      ~~~~~~~~~~~~~~~~~~~^~~~
/home/umireon/obs-ocr/vendor/inja/include/inja/exceptions.hpp:15:21: note: shadowed declaration is here
   15 |   const std::string type;
      |                     ^~~~
/home/umireon/obs-ocr/vendor/inja/include/inja/exceptions.hpp: In constructor ‘inja::InjaError::InjaError(const std::string&, const std::string&)’:
/home/umireon/obs-ocr/vendor/inja/include/inja/exceptions.hpp:20:66: error: declaration of ‘message’ shadows a member of ‘inja::InjaError’ [-Werror=shadow]
   20 |   explicit InjaError(const std::string& type, const std::string& message)
      |                                               ~~~~~~~~~~~~~~~~~~~^~~~~~~
/home/umireon/obs-ocr/vendor/inja/include/inja/exceptions.hpp:16:21: note: shadowed declaration is here
   16 |   const std::string message;
      |                     ^~~~~~~
/home/umireon/obs-ocr/vendor/inja/include/inja/exceptions.hpp:20:41: error: declaration of ‘type’ shadows a member of ‘inja::InjaError’ [-Werror=shadow]
   20 |   explicit InjaError(const std::string& type, const std::string& message)
      |                      ~~~~~~~~~~~~~~~~~~~^~~~
/home/umireon/obs-ocr/vendor/inja/include/inja/exceptions.hpp:15:21: note: shadowed declaration is here
   15 |   const std::string type;
      |                     ^~~~
/home/umireon/obs-ocr/vendor/inja/include/inja/exceptions.hpp: In constructor ‘inja::InjaError::InjaError(const std::string&, const std::string&)’:
/home/umireon/obs-ocr/vendor/inja/include/inja/exceptions.hpp:20:66: error: declaration of ‘message’ shadows a member of ‘inja::InjaError’ [-Werror=shadow]
   20 |   explicit InjaError(const std::string& type, const std::string& message)
      |                                               ~~~~~~~~~~~~~~~~~~~^~~~~~~
/home/umireon/obs-ocr/vendor/inja/include/inja/exceptions.hpp:16:21: note: shadowed declaration is here
   16 |   const std::string message;
      |                     ^~~~~~~
/home/umireon/obs-ocr/vendor/inja/include/inja/exceptions.hpp:20:41: error: declaration of ‘type’ shadows a member of ‘inja::InjaError’ [-Werror=shadow]
   20 |   explicit InjaError(const std::string& type, const std::string& message)
      |                      ~~~~~~~~~~~~~~~~~~~^~~~
/home/umireon/obs-ocr/vendor/inja/include/inja/exceptions.hpp:15:21: note: shadowed declaration is here
   15 |   const std::string type;
      |                     ^~~~
/home/umireon/obs-ocr/vendor/inja/include/inja/exceptions.hpp: In constructor ‘inja::InjaError::InjaError(const std::string&, const std::string&, inja::SourceLocation)’:
/home/umireon/obs-ocr/vendor/inja/include/inja/exceptions.hpp:23:90: error: declaration of ‘location’ shadows a member of ‘inja::InjaError’ [-Werror=shadow]
   23 |   explicit InjaError(const std::string& type, const std::string& message, SourceLocation location)
      |                                                                           ~~~~~~~~~~~~~~~^~~~~~~~
/home/umireon/obs-ocr/ve [...]

2024-01-26 17:55 UTC, umireon commented
I'm sure the no-error=shadow option was added. I suppose you need to fork inja to suppress this warning.

2024-01-26 17:56 UTC, umireon commented
```
[umireon@fedora-from-source obs-ocr]$ git log
commit 2b7fa6293166bf071bc19cc989c312b4a4a4afbb (HEAD -> roy.fedora_instructions_build, origin/roy.fedora_instructions_build)
Author: Roy Shilkrot <roy.shil@gmail.com>
Date:   Fri Jan 26 12:36:33 2024 -0500

    Disable conversion errors on Linux

commit addb9233a7a2970884bfe25a057770a6f7cfd217
Author: Roy Shilkrot <roy.shil@gmail.com>
Date:   Fri Jan 26 12:34:42 2024 -0500

    Disable shadowing warnings in inja build

commit 78d1356317f33f7886f8f1c8ef54e87f6b122dd7
Merge: 3f23c34 7f953e2
Author: Roy Shilkrot <roy.shil@gmail.com>
Date:   Fri Jan 26 12:30:30 2024 -0500

    Merge branch 'roy.fedora_instructions_build' of github.com:occ-ai/obs-ocr into roy.fedora_instructions_build
```

2024-01-29 05:50 UTC, royshil commented
@umireon with removing the -Wshadow from the linux compiler flags - i'm able to build this on Fedora docker with the instructions provided

2024-01-29 17:20 UTC, umireon approved these changes
LGTM

2024-01-29 19:19 UTC, merged